### ISSUE TITLE
Fortran-tags documentation for intrinsic Fortran procedures

### ISSUE THREAD

**Issue by AstroFloyd** [raullaasner/fortran-tags#2]
Hi there!  No issue, just a comment.

I was playing with Fortran-tags - very nice! :-)  Some time ago, I wrote a script to convert GFortran HTML documentation to manpage format.  I now wrote a second script that converts the manpages to (commented-out, except for the procedure prototype) Fortran.  Hence, Fortran-tags can use these files and provide documentation on syntax and examples for many intrinsic Fortran procedures.  If you're interested, you can find the files and more details [here](https://github.com/AstroFloyd/man-pages-fortran/).

Cheers!

**Comment by raullaasner** [comment]
Very cool! I'll have a look at it.
