### ISSUE TITLE
Remote FORTAGS file

### ISSUE THREAD

**Issue by findesgh** [raullaasner/fortran-tags#3]
Is it possible to use a remote FORTAGS file? I have a project on a remote server and often work on it using TRAMP. When I try to use the FORTAGS file generated on the remote server with my local instance of emacs, I get an `Incorrect format (regenerate using the current version of Fortran-tags)` error.

**Comment by raullaasner** [comment]
It is currently not implemented but it's a good idea! I started implementing it and I'll let you know when it's finished.
