### ISSUE TITLE
Indirect buffers

### ISSUE THREAD

**Issue by findesgh** [raullaasner/fortran-tags#4]
When running `fortran-find-tag` in an indirect buffer, the cursor jumps to the associated base buffer if the definition is in the same file. It would be nice if this weren't the case. Unfortunately, my `lisp` skills are very limited and this issue does not bother me very much, so I'm opening it mainly for documentation purposes.

**Comment by raullaasner** [comment]
I produced a fix. Let me know if this is still an issue.

**Comment by findesgh** [comment]
Wow, thanks for the quick reply and fix.

One small issue I found was with filenames including symlinks or relative paths. I've created a small fix for that. Not a lisp guru, there might be a better or nicer way.

Let me know.
