### ISSUE TITLE
Why not implement a pure elisp package instead of depending on python for processing Fortran source code? 

### ISSUE THREAD

**Issue by hongyi-zhao** [raullaasner/fortran-tags#9]
I noticed this package [depends on python for processing Fortran source code](https://github.com/raullaasner/fortran-tags/blob/master/fortran-tags.py). Why not implement a pure elisp package instead of depending on python for processing Fortran source code? 

Regards,
HY

**Comment by raullaasner** [comment]
Hi, thanks for the comment! I'm much more familiar with Pyhon than Elisp, especially when it comes to text parsing. That's basically it. ¯\_(ツ)_/¯
